#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kolnikApp_komponente
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.Runtime.Serialization;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "16001_DB")]
    public partial class DataClasses1DataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void Insertartikl(artikl instance);
        partial void Updateartikl(artikl instance);
        partial void Deleteartikl(artikl instance);
        partial void Insertosoba(osoba instance);
        partial void Updateosoba(osoba instance);
        partial void Deleteosoba(osoba instance);
        partial void Insertkorisnicki_racun(korisnicki_racun instance);
        partial void Updatekorisnicki_racun(korisnicki_racun instance);
        partial void Deletekorisnicki_racun(korisnicki_racun instance);
        partial void Insertnarudzbenica_bitumenske_mjesavine(narudzbenica_bitumenske_mjesavine instance);
        partial void Updatenarudzbenica_bitumenske_mjesavine(narudzbenica_bitumenske_mjesavine instance);
        partial void Deletenarudzbenica_bitumenske_mjesavine(narudzbenica_bitumenske_mjesavine instance);
        partial void Insertotpremnica(otpremnica instance);
        partial void Updateotpremnica(otpremnica instance);
        partial void Deleteotpremnica(otpremnica instance);
        partial void Insertpoduzece(poduzece instance);
        partial void Updatepoduzece(poduzece instance);
        partial void Deletepoduzece(poduzece instance);
        partial void Insertrabat(rabat instance);
        partial void Updaterabat(rabat instance);
        partial void Deleterabat(rabat instance);
        partial void Insertracun(racun instance);
        partial void Updateracun(racun instance);
        partial void Deleteracun(racun instance);
        partial void Insertradno_mjesto(radno_mjesto instance);
        partial void Updateradno_mjesto(radno_mjesto instance);
        partial void Deleteradno_mjesto(radno_mjesto instance);
        partial void Inserttablicna_privilegija(tablicna_privilegija instance);
        partial void Updatetablicna_privilegija(tablicna_privilegija instance);
        partial void Deletetablicna_privilegija(tablicna_privilegija instance);
        partial void Insertproizvodni_nalog(proizvodni_nalog instance);
        partial void Updateproizvodni_nalog(proizvodni_nalog instance);
        partial void Deleteproizvodni_nalog(proizvodni_nalog instance);
        partial void Insertvozi(vozi instance);
        partial void Updatevozi(vozi instance);
        partial void Deletevozi(vozi instance);
        partial void Insertvozilo(vozilo instance);
        partial void Updatevozilo(vozilo instance);
        partial void Deletevozilo(vozilo instance);
        partial void Insertzaposlen(zaposlen instance);
        partial void Updatezaposlen(zaposlen instance);
        partial void Deletezaposlen(zaposlen instance);
        #endregion

        public DataClasses1DataContext() :
                base(global::kolnikApp_komponente.Properties.Settings.Default._16001_DBConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<artikl> artikls
        {
            get
            {
                return this.GetTable<artikl>();
            }
        }

        public System.Data.Linq.Table<osoba> osobas
        {
            get
            {
                return this.GetTable<osoba>();
            }
        }

        public System.Data.Linq.Table<korisnicki_racun> korisnicki_racuns
        {
            get
            {
                return this.GetTable<korisnicki_racun>();
            }
        }

        public System.Data.Linq.Table<narudzbenica_bitumenske_mjesavine> narudzbenica_bitumenske_mjesavines
        {
            get
            {
                return this.GetTable<narudzbenica_bitumenske_mjesavine>();
            }
        }

        public System.Data.Linq.Table<otpremnica> otpremnicas
        {
            get
            {
                return this.GetTable<otpremnica>();
            }
        }

        public System.Data.Linq.Table<poduzece> poduzeces
        {
            get
            {
                return this.GetTable<poduzece>();
            }
        }

        public System.Data.Linq.Table<rabat> rabats
        {
            get
            {
                return this.GetTable<rabat>();
            }
        }

        public System.Data.Linq.Table<racun> racuns
        {
            get
            {
                return this.GetTable<racun>();
            }
        }

        public System.Data.Linq.Table<radno_mjesto> radno_mjestos
        {
            get
            {
                return this.GetTable<radno_mjesto>();
            }
        }

        public System.Data.Linq.Table<tablicna_privilegija> tablicna_privilegijas
        {
            get
            {
                return this.GetTable<tablicna_privilegija>();
            }
        }

        public System.Data.Linq.Table<proizvodni_nalog> proizvodni_nalogs
        {
            get
            {
                return this.GetTable<proizvodni_nalog>();
            }
        }

        public System.Data.Linq.Table<vozi> vozis
        {
            get
            {
                return this.GetTable<vozi>();
            }
        }

        public System.Data.Linq.Table<vozilo> vozilos
        {
            get
            {
                return this.GetTable<vozilo>();
            }
        }

        public System.Data.Linq.Table<zaposlen> zaposlens
        {
            get
            {
                return this.GetTable<zaposlen>();
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.artikl")]
    public partial class artikl : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _naziv;

        private decimal _jedinicna_cijena;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void OnnazivChanging(string value);
        partial void OnnazivChanged();
        partial void Onjedinicna_cijenaChanging(decimal value);
        partial void Onjedinicna_cijenaChanged();
        #endregion

        public artikl()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_naziv", DbType = "VarChar(100) NOT NULL", CanBeNull = false)]
        public string naziv
        {
            get
            {
                return this._naziv;
            }
            set
            {
                if ((this._naziv != value))
                {
                    this.OnnazivChanging(value);
                    this.SendPropertyChanging();
                    this._naziv = value;
                    this.SendPropertyChanged("naziv");
                    this.OnnazivChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_jedinicna_cijena", DbType = "Decimal(9,2) NOT NULL")]
        public decimal jedinicna_cijena
        {
            get
            {
                return this._jedinicna_cijena;
            }
            set
            {
                if ((this._jedinicna_cijena != value))
                {
                    this.Onjedinicna_cijenaChanging(value);
                    this.SendPropertyChanging();
                    this._jedinicna_cijena = value;
                    this.SendPropertyChanged("jedinicna_cijena");
                    this.Onjedinicna_cijenaChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.osoba")]
    public partial class osoba : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _oib;

        private string _ime;

        private string _prezime;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnoibChanging(string value);
        partial void OnoibChanged();
        partial void OnimeChanging(string value);
        partial void OnimeChanged();
        partial void OnprezimeChanging(string value);
        partial void OnprezimeChanged();
        #endregion

        public osoba()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_oib", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string oib
        {
            get
            {
                return this._oib;
            }
            set
            {
                if ((this._oib != value))
                {
                    this.OnoibChanging(value);
                    this.SendPropertyChanging();
                    this._oib = value;
                    this.SendPropertyChanged("oib");
                    this.OnoibChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ime", DbType = "VarChar(45) NOT NULL", CanBeNull = false)]
        public string ime
        {
            get
            {
                return this._ime;
            }
            set
            {
                if ((this._ime != value))
                {
                    this.OnimeChanging(value);
                    this.SendPropertyChanging();
                    this._ime = value;
                    this.SendPropertyChanged("ime");
                    this.OnimeChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_prezime", DbType = "VarChar(45) NOT NULL", CanBeNull = false)]
        public string prezime
        {
            get
            {
                return this._prezime;
            }
            set
            {
                if ((this._prezime != value))
                {
                    this.OnprezimeChanging(value);
                    this.SendPropertyChanging();
                    this._prezime = value;
                    this.SendPropertyChanged("prezime");
                    this.OnprezimeChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.korisnicki_racun")]
    public partial class korisnicki_racun : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _zaposlenik;

        private string _korisnicko_ime;

        private string _lozinka;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnzaposlenikChanging(string value);
        partial void OnzaposlenikChanged();
        partial void Onkorisnicko_imeChanging(string value);
        partial void Onkorisnicko_imeChanged();
        partial void OnlozinkaChanging(string value);
        partial void OnlozinkaChanged();
        #endregion

        public korisnicki_racun()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_zaposlenik", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string zaposlenik
        {
            get
            {
                return this._zaposlenik;
            }
            set
            {
                if ((this._zaposlenik != value))
                {
                    this.OnzaposlenikChanging(value);
                    this.SendPropertyChanging();
                    this._zaposlenik = value;
                    this.SendPropertyChanged("zaposlenik");
                    this.OnzaposlenikChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_korisnicko_ime", DbType = "VarChar(45) NOT NULL", CanBeNull = false)]
        public string korisnicko_ime
        {
            get
            {
                return this._korisnicko_ime;
            }
            set
            {
                if ((this._korisnicko_ime != value))
                {
                    this.Onkorisnicko_imeChanging(value);
                    this.SendPropertyChanging();
                    this._korisnicko_ime = value;
                    this.SendPropertyChanged("korisnicko_ime");
                    this.Onkorisnicko_imeChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_lozinka", DbType = "Char(40) NOT NULL", CanBeNull = false)]
        public string lozinka
        {
            get
            {
                return this._lozinka;
            }
            set
            {
                if ((this._lozinka != value))
                {
                    this.OnlozinkaChanging(value);
                    this.SendPropertyChanging();
                    this._lozinka = value;
                    this.SendPropertyChanged("lozinka");
                    this.OnlozinkaChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.narudzbenica_bitumenske_mjesavine")]
    public partial class narudzbenica_bitumenske_mjesavine : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private System.DateTime _datum_izdavanja;

        private System.DateTime _datum_potrazivanja;

        private string _izdavatelj;

        private decimal _kolicina;

        private int _vozi;

        private int _artikl;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Ondatum_izdavanjaChanging(System.DateTime value);
        partial void Ondatum_izdavanjaChanged();
        partial void Ondatum_potrazivanjaChanging(System.DateTime value);
        partial void Ondatum_potrazivanjaChanged();
        partial void OnkolicinaChanging(decimal value);
        partial void OnkolicinaChanged();
        partial void OnvoziChanging(int value);
        partial void OnvoziChanged();
        partial void OnartiklChanging(int value);
        partial void OnartiklChanged();
        partial void OnizdavateljChanging(string value);
        partial void OnizdavateljChanged();

        #endregion

        public narudzbenica_bitumenske_mjesavine()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_izdavanja", DbType = "DateTime NOT NULL")]
        public System.DateTime datum_izdavanja
        {
            get
            {
                return this._datum_izdavanja;
            }
            set
            {
                if ((this._datum_izdavanja != value))
                {
                    this.Ondatum_izdavanjaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_izdavanja = value;
                    this.SendPropertyChanged("datum_izdavanja");
                    this.Ondatum_izdavanjaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_potrazivanja", DbType = "DateTime NOT NULL")]
        public System.DateTime datum_potrazivanja
        {
            get
            {
                return this._datum_potrazivanja;
            }
            set
            {
                if ((this._datum_potrazivanja != value))
                {
                    this.Ondatum_potrazivanjaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_potrazivanja = value;
                    this.SendPropertyChanged("datum_potrazivanja");
                    this.Ondatum_potrazivanjaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_izdavatelj", DbType = "Char(11) NOT NULL", CanBeNull = false)]
        public string izdavatelj
        {
            get
            {
                return this._izdavatelj;
            }
            set
            {
                if ((this._izdavatelj != value))
                {
                    this.OnizdavateljChanging(value);
                    this.SendPropertyChanging();
                    this._izdavatelj = value;
                    this.SendPropertyChanged("izdavatelj");
                    this.OnizdavateljChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_kolicina", DbType = "Decimal(5,3) NOT NULL")]
        public decimal kolicina
        {
            get
            {
                return this._kolicina;
            }
            set
            {
                if ((this._kolicina != value))
                {
                    this.OnkolicinaChanging(value);
                    this.SendPropertyChanging();
                    this._kolicina = value;
                    this.SendPropertyChanged("kolicina");
                    this.OnkolicinaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vozi", DbType = "Int NOT NULL", CanBeNull = false)]
        public int vozi
        {
            get
            {
                return this._vozi;
            }
            set
            {
                if ((this._vozi != value))
                {
                    this.OnvoziChanging(value);
                    this.SendPropertyChanging();
                    this._vozi = value;
                    this.SendPropertyChanged("vozi");
                    this.OnvoziChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_artikl", DbType = "Int NOT NULL")]
        public int artikl
        {
            get
            {
                return this._artikl;
            }
            set
            {
                if ((this._artikl != value))
                {
                    this.OnartiklChanging(value);
                    this.SendPropertyChanging();
                    this._artikl = value;
                    this.SendPropertyChanged("artikl");
                    this.OnartiklChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.otpremnica")]
    public partial class otpremnica : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _nalog;

        private System.DateTime _datum_otpreme;

        private System.Nullable<int> _racun;

        private string _otpremitelj;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnnalogChanging(int value);
        partial void OnnalogChanged();
        partial void Ondatum_otpremeChanging(System.DateTime value);
        partial void Ondatum_otpremeChanged();
        partial void OnracunChanging(System.Nullable<int> value);
        partial void OnracunChanged();
        partial void OnotpremiteljChanging(string value);
        partial void OnotpremiteljChanged();
        #endregion

        public otpremnica()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_nalog", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int nalog
        {
            get
            {
                return this._nalog;
            }
            set
            {
                if ((this._nalog != value))
                {
                    this.OnnalogChanging(value);
                    this.SendPropertyChanging();
                    this._nalog = value;
                    this.SendPropertyChanged("nalog");
                    this.OnnalogChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_otpreme", DbType = "DateTime NOT NULL")]
        public System.DateTime datum_otpreme
        {
            get
            {
                return this._datum_otpreme;
            }
            set
            {
                if ((this._datum_otpreme != value))
                {
                    this.Ondatum_otpremeChanging(value);
                    this.SendPropertyChanging();
                    this._datum_otpreme = value;
                    this.SendPropertyChanged("datum_otpreme");
                    this.Ondatum_otpremeChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_racun", DbType = "Int")]
        public System.Nullable<int> racun
        {
            get
            {
                return this._racun;
            }
            set
            {
                if ((this._racun != value))
                {
                    this.OnracunChanging(value);
                    this.SendPropertyChanging();
                    this._racun = value;
                    this.SendPropertyChanged("racun");
                    this.OnracunChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_otpremitelj", DbType = "Char(11) NOT NULL", CanBeNull = false)]
        public string otpremitelj
        {
            get
            {
                return this._otpremitelj;
            }
            set
            {
                if ((this._otpremitelj != value))
                {
                    this.OnotpremiteljChanging(value);
                    this.SendPropertyChanging();
                    this._otpremitelj = value;
                    this.SendPropertyChanged("otpremitelj");
                    this.OnotpremiteljChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.poduzece")]
    public partial class poduzece : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _oib;

        private string _naziv;

        private string _adresa;

        private string _iban;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnoibChanging(string value);
        partial void OnoibChanged();
        partial void OnnazivChanging(string value);
        partial void OnnazivChanged();
        partial void OnadresaChanging(string value);
        partial void OnadresaChanged();
        partial void OnibanChanging(string value);
        partial void OnibanChanged();
        #endregion

        public poduzece()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_oib", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string oib
        {
            get
            {
                return this._oib;
            }
            set
            {
                if ((this._oib != value))
                {
                    this.OnoibChanging(value);
                    this.SendPropertyChanging();
                    this._oib = value;
                    this.SendPropertyChanged("oib");
                    this.OnoibChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_naziv", DbType = "VarChar(100) NOT NULL", CanBeNull = false)]
        public string naziv
        {
            get
            {
                return this._naziv;
            }
            set
            {
                if ((this._naziv != value))
                {
                    this.OnnazivChanging(value);
                    this.SendPropertyChanging();
                    this._naziv = value;
                    this.SendPropertyChanged("naziv");
                    this.OnnazivChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_adresa", DbType = "VarChar(100)")]
        public string adresa
        {
            get
            {
                return this._adresa;
            }
            set
            {
                if ((this._adresa != value))
                {
                    this.OnadresaChanging(value);
                    this.SendPropertyChanging();
                    this._adresa = value;
                    this.SendPropertyChanged("adresa");
                    this.OnadresaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_iban", DbType = "VarChar(34)")]
        public string iban
        {
            get
            {
                return this._iban;
            }
            set
            {
                if ((this._iban != value))
                {
                    this.OnibanChanging(value);
                    this.SendPropertyChanging();
                    this._iban = value;
                    this.SendPropertyChanged("iban");
                    this.OnibanChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.rabat")]
    public partial class rabat : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _artikl;

        private string _poslovni_partner;

        private decimal _popust;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnartiklChanging(int value);
        partial void OnartiklChanged();
        partial void Onposlovni_partnerChanging(string value);
        partial void Onposlovni_partnerChanged();
        partial void OnpopustChanging(decimal value);
        partial void OnpopustChanged();
        #endregion

        public rabat()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_artikl", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int artikl
        {
            get
            {
                return this._artikl;
            }
            set
            {
                if ((this._artikl != value))
                {
                    this.OnartiklChanging(value);
                    this.SendPropertyChanging();
                    this._artikl = value;
                    this.SendPropertyChanged("artikl");
                    this.OnartiklChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_poslovni_partner", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string poslovni_partner
        {
            get
            {
                return this._poslovni_partner;
            }
            set
            {
                if ((this._poslovni_partner != value))
                {
                    this.Onposlovni_partnerChanging(value);
                    this.SendPropertyChanging();
                    this._poslovni_partner = value;
                    this.SendPropertyChanged("poslovni_partner");
                    this.Onposlovni_partnerChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_popust", DbType = "Decimal(5,3) NOT NULL")]
        public decimal popust
        {
            get
            {
                return this._popust;
            }
            set
            {
                if ((this._popust != value))
                {
                    this.OnpopustChanging(value);
                    this.SendPropertyChanging();
                    this._popust = value;
                    this.SendPropertyChanged("popust");
                    this.OnpopustChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.racun")]
    public partial class racun : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private System.DateTime _datum_izdavanja;

        private string _izdavatelj;

        private bool _placeno;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Ondatum_izdavanjaChanging(System.DateTime value);
        partial void Ondatum_izdavanjaChanged();
        partial void OnizdavateljChanging(string value);
        partial void OnizdavateljChanged();
        partial void OnplacenoChanging(bool value);
        partial void OnplacenoChanged();
        #endregion

        public racun()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_izdavanja", DbType = "DateTime NOT NULL")]
        public System.DateTime datum_izdavanja
        {
            get
            {
                return this._datum_izdavanja;
            }
            set
            {
                if ((this._datum_izdavanja != value))
                {
                    this.Ondatum_izdavanjaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_izdavanja = value;
                    this.SendPropertyChanged("datum_izdavanja");
                    this.Ondatum_izdavanjaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_izdavatelj", DbType = "Char(11) NOT NULL", CanBeNull = false)]
        public string izdavatelj
        {
            get
            {
                return this._izdavatelj;
            }
            set
            {
                if ((this._izdavatelj != value))
                {
                    this.OnizdavateljChanging(value);
                    this.SendPropertyChanging();
                    this._izdavatelj = value;
                    this.SendPropertyChanged("izdavatelj");
                    this.OnizdavateljChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_placeno", DbType = "Bit NOT NULL")]
        public bool placeno
        {
            get
            {
                return this._placeno;
            }
            set
            {
                if ((this._placeno != value))
                {
                    this.OnplacenoChanging(value);
                    this.SendPropertyChanging();
                    this._placeno = value;
                    this.SendPropertyChanged("placeno");
                    this.OnplacenoChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.radno_mjesto")]
    public partial class radno_mjesto : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _naziv;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void OnnazivChanging(string value);
        partial void OnnazivChanged();
        #endregion

        public radno_mjesto()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_naziv", DbType = "VarChar(45) NOT NULL", CanBeNull = false)]
        public string naziv
        {
            get
            {
                return this._naziv;
            }
            set
            {
                if ((this._naziv != value))
                {
                    this.OnnazivChanging(value);
                    this.SendPropertyChanging();
                    this._naziv = value;
                    this.SendPropertyChanged("naziv");
                    this.OnnazivChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.tablicna_privilegija")]
    public partial class tablicna_privilegija : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _radno_mjesto;

        private string _naziv_tablice;

        private byte _operacija;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void Onradno_mjestoChanging(int value);
        partial void Onradno_mjestoChanged();
        partial void Onnaziv_tabliceChanging(string value);
        partial void Onnaziv_tabliceChanged();
        partial void OnoperacijaChanging(byte value);
        partial void OnoperacijaChanged();
        #endregion

        public tablicna_privilegija()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_radno_mjesto", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int radno_mjesto
        {
            get
            {
                return this._radno_mjesto;
            }
            set
            {
                if ((this._radno_mjesto != value))
                {
                    this.Onradno_mjestoChanging(value);
                    this.SendPropertyChanging();
                    this._radno_mjesto = value;
                    this.SendPropertyChanged("radno_mjesto");
                    this.Onradno_mjestoChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_naziv_tablice", DbType = "VarChar(50) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string naziv_tablice
        {
            get
            {
                return this._naziv_tablice;
            }
            set
            {
                if ((this._naziv_tablice != value))
                {
                    this.Onnaziv_tabliceChanging(value);
                    this.SendPropertyChanging();
                    this._naziv_tablice = value;
                    this.SendPropertyChanged("naziv_tablice");
                    this.Onnaziv_tabliceChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_operacija", DbType = "TinyInt NOT NULL")]
        public byte operacija
        {
            get
            {
                return this._operacija;
            }
            set
            {
                if ((this._operacija != value))
                {
                    this.OnoperacijaChanging(value);
                    this.SendPropertyChanging();
                    this._operacija = value;
                    this.SendPropertyChanged("operacija");
                    this.OnoperacijaChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.proizvodni_nalog")]
    public partial class proizvodni_nalog : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _narudzbenica;

        private System.DateTime _datum_izdavanja;

        private string _izdavatelj;

        private int _temperatura;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnnarudzbenicaChanging(int value);
        partial void OnnarudzbenicaChanged();
        partial void Ondatum_izdavanjaChanging(System.DateTime value);
        partial void Ondatum_izdavanjaChanged();
        partial void OntemperaturaChanging(int value);
        partial void OntemperaturaChanged();
        partial void OnizdavateljChanging(string value);
        partial void OnizdavateljChanged();
        #endregion

        public proizvodni_nalog()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_narudzbenica", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int narudzbenica
        {
            get
            {
                return this._narudzbenica;
            }
            set
            {
                if ((this._narudzbenica != value))
                {
                    this.OnnarudzbenicaChanging(value);
                    this.SendPropertyChanging();
                    this._narudzbenica = value;
                    this.SendPropertyChanged("narudzbenica");
                    this.OnnarudzbenicaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_izdavanja", DbType = "DateTime NOT NULL")]
        public System.DateTime datum_izdavanja
        {
            get
            {
                return this._datum_izdavanja;
            }
            set
            {
                if ((this._datum_izdavanja != value))
                {
                    this.Ondatum_izdavanjaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_izdavanja = value;
                    this.SendPropertyChanged("datum_izdavanja");
                    this.Ondatum_izdavanjaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_izdavatelj", DbType = "Char(11) NOT NULL")]
        public string izdavatelj
        {
            get
            {
                return this._izdavatelj;
            }
            set
            {
                if ((this._izdavatelj != value))
                {
                    this.OnizdavateljChanging(value);
                    this.SendPropertyChanging();
                    this._izdavatelj = value;
                    this.SendPropertyChanged("izdavatelj");
                    this.OnizdavateljChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_temperatura", DbType = "Int NOT NULL")]
        public int temperatura
        {
            get
            {
                return this._temperatura;
            }
            set
            {
                if ((this._temperatura != value))
                {
                    this.OntemperaturaChanging(value);
                    this.SendPropertyChanging();
                    this._temperatura = value;
                    this.SendPropertyChanged("temperatura");
                    this.OntemperaturaChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.vozi")]
    public partial class vozi : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _vozilo;

        private string _vozac;

        private System.DateTime _datum_pocetka;

        private System.Nullable<System.DateTime> _datum_zavrsetka;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void OnvoziloChanging(string value);
        partial void OnvoziloChanged();
        partial void OnvozacChanging(string value);
        partial void OnvozacChanged();
        partial void Ondatum_pocetkaChanging(System.DateTime value);
        partial void Ondatum_pocetkaChanged();
        partial void Ondatum_zavrsetkaChanging(System.Nullable<System.DateTime> value);
        partial void Ondatum_zavrsetkaChanged();
        #endregion

        public vozi()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vozilo", DbType = "VarChar(8) NOT NULL", CanBeNull = false, IsPrimaryKey = false)]
        public string vozilo
        {
            get
            {
                return this._vozilo;
            }
            set
            {
                if ((this._vozilo != value))
                {
                    this.OnvoziloChanging(value);
                    this.SendPropertyChanging();
                    this._vozilo = value;
                    this.SendPropertyChanged("vozilo");
                    this.OnvoziloChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vozac", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = false)]
        public string vozac
        {
            get
            {
                return this._vozac;
            }
            set
            {
                if ((this._vozac != value))
                {
                    this.OnvozacChanging(value);
                    this.SendPropertyChanging();
                    this._vozac = value;
                    this.SendPropertyChanged("vozac");
                    this.OnvozacChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_pocetka", DbType = "Date NOT NULL", IsPrimaryKey = false)]
        public System.DateTime datum_pocetka
        {
            get
            {
                return this._datum_pocetka;
            }
            set
            {
                if ((this._datum_pocetka != value))
                {
                    this.Ondatum_pocetkaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_pocetka = value;
                    this.SendPropertyChanged("datum_pocetka");
                    this.Ondatum_pocetkaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_zavrsetka", DbType = "Date")]
        public System.Nullable<System.DateTime> datum_zavrsetka
        {
            get
            {
                return this._datum_zavrsetka;
            }
            set
            {
                if ((this._datum_zavrsetka != value))
                {
                    this.Ondatum_zavrsetkaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_zavrsetka = value;
                    this.SendPropertyChanged("datum_zavrsetka");
                    this.Ondatum_zavrsetkaChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(IsReference = true, Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.vozilo")]
    public partial class vozilo : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _registracijski_broj;

        private string _proizvodjac;

        private string _model;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void Onregistracijski_brojChanging(string value);
        partial void Onregistracijski_brojChanged();
        partial void OnproizvodjacChanging(string value);
        partial void OnproizvodjacChanged();
        partial void OnmodelChanging(string value);
        partial void OnmodelChanged();
        #endregion

        public vozilo()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_registracijski_broj", DbType = "VarChar(8) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string registracijski_broj
        {
            get
            {
                return this._registracijski_broj;
            }
            set
            {
                if ((this._registracijski_broj != value))
                {
                    this.Onregistracijski_brojChanging(value);
                    this.SendPropertyChanging();
                    this._registracijski_broj = value;
                    this.SendPropertyChanged("registracijski_broj");
                    this.Onregistracijski_brojChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_proizvodjac", DbType = "VarChar(45)")]
        public string proizvodjac
        {
            get
            {
                return this._proizvodjac;
            }
            set
            {
                if ((this._proizvodjac != value))
                {
                    this.OnproizvodjacChanging(value);
                    this.SendPropertyChanging();
                    this._proizvodjac = value;
                    this.SendPropertyChanged("proizvodjac");
                    this.OnproizvodjacChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_model", DbType = "VarChar(45)")]
        public string model
        {
            get
            {
                return this._model;
            }
            set
            {
                if ((this._model != value))
                {
                    this.OnmodelChanging(value);
                    this.SendPropertyChanging();
                    this._model = value;
                    this.SendPropertyChanged("model");
                    this.OnmodelChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [DataContract(Namespace = "")]
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.zaposlen")]
    public partial class zaposlen : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _zaposlenik;

        private string _poduzece;

        private System.DateTime _datum_pocetka;

        private System.Nullable<System.DateTime> _datum_zavrsetka;

        private int _radno_mjesto;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void OnzaposlenikChanging(string value);
        partial void OnzaposlenikChanged();
        partial void OnpoduzeceChanging(string value);
        partial void OnpoduzeceChanged();
        partial void Ondatum_pocetkaChanging(System.DateTime value);
        partial void Ondatum_pocetkaChanged();
        partial void Ondatum_zavrsetkaChanging(System.Nullable<System.DateTime> value);
        partial void Ondatum_zavrsetkaChanged();
        partial void Onradno_mjestoChanging(int value);
        partial void Onradno_mjestoChanged();
        #endregion

        public zaposlen()
        {
            OnCreated();
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_zaposlenik", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = false)]
        public string zaposlenik
        {
            get
            {
                return this._zaposlenik;
            }
            set
            {
                if ((this._zaposlenik != value))
                {
                    this.OnzaposlenikChanging(value);
                    this.SendPropertyChanging();
                    this._zaposlenik = value;
                    this.SendPropertyChanged("zaposlenik");
                    this.OnzaposlenikChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_poduzece", DbType = "Char(11) NOT NULL", CanBeNull = false, IsPrimaryKey = false)]
        public string poduzece
        {
            get
            {
                return this._poduzece;
            }
            set
            {
                if ((this._poduzece != value))
                {
                    this.OnpoduzeceChanging(value);
                    this.SendPropertyChanging();
                    this._poduzece = value;
                    this.SendPropertyChanged("poduzece");
                    this.OnpoduzeceChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_pocetka", DbType = "Date NOT NULL", IsPrimaryKey = false)]
        public System.DateTime datum_pocetka
        {
            get
            {
                return this._datum_pocetka;
            }
            set
            {
                if ((this._datum_pocetka != value))
                {
                    this.Ondatum_pocetkaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_pocetka = value;
                    this.SendPropertyChanged("datum_pocetka");
                    this.Ondatum_pocetkaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_datum_zavrsetka", DbType = "Date")]
        public System.Nullable<System.DateTime> datum_zavrsetka
        {
            get
            {
                return this._datum_zavrsetka;
            }
            set
            {
                if ((this._datum_zavrsetka != value))
                {
                    this.Ondatum_zavrsetkaChanging(value);
                    this.SendPropertyChanging();
                    this._datum_zavrsetka = value;
                    this.SendPropertyChanged("datum_zavrsetka");
                    this.Ondatum_zavrsetkaChanged();
                }
            }
        }

        [DataMemberAttribute]
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_radno_mjesto", DbType = "Int NOT NULL", CanBeNull = false, IsPrimaryKey = false)]
        public int radno_mjesto
        {
            get
            {
                return this._radno_mjesto;
            }
            set
            {
                if ((this._radno_mjesto != value))
                {
                    this.Onradno_mjestoChanging(value);
                    this.SendPropertyChanging();
                    this._radno_mjesto = value;
                    this.SendPropertyChanged("radno_mjesto");
                    this.Onradno_mjestoChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
